services:
  api:
    build: ./api
    container_name: projetdocker-api
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: projetdocker-mongo
    command: ["--dbpath", "/data/db"]
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/gamesdb", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1
    container_name: projetdocker-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
